version: '3'

services:
    gomdb:
      image: mongo:latest
      container_name: portfoliomdb
      # restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

      ports:
        - "27017:27017"
      volumes:
        - mdbdata:/data/db
volumes:
    mdbdata:
