version: '3'

services:
    portfoliomdb:
      image: mongo:latest
      container_name: portfoliomdb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

      ports:
        - "27017:27017"
      volumes:
        - mdbdata:/data/db
    goapp:
      image: gowebapp:latest
      container_name: localapp
      depends_on:
        - "portfoliomdb"
      #restart: always
      links:
        - "portfoliomdb"
      build:
        context: .
        dockerfile: "Portfoliofile.goapp"

      ports:
        - "9000:9000"
volumes:
    mdbdata:

