FROM golang:latest AS build

WORKDIR /Abgabe
COPY ./main.go .
RUN mkdir -p vendor
COPY go.mod .
COPY go.sum .
RUN go mod vendor
RUN go build -o PortfolioApp main.go

FROM debian
WORKDIR /Abgabe
COPY --from=build /Abgabe/PortfolioApp .
COPY static/ static/
COPY raw/ raw/
EXPOSE 9000
CMD ["/Abgabe/PortfolioApp"]